"
I stores metadata on true and false positive critics. These meta data are used by the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPhratchMotion,
	#superclass : #Object,
	#category : #PhratchMotion
}

{ #category : #'meta data' }
ManifestPhratchMotion class >> rejectClasses [
^ #()
]

{ #category : #'meta data' }
ManifestPhratchMotion class >> rejectRules [
^ #()
]
