Class {
	#name : #PhratchCategoryFiles,
	#superclass : #PhratchCategory,
	#category : #'Phratch-Categories'
}

{ #category : #'as yet unclassified' }
PhratchCategoryFiles class >> color [
	^(Color r: 0.17254901960784313725490196078431 g: 0.47058823529411764705882352941176 b: 0.76470588235294117647058823529412)
]

{ #category : #'as yet unclassified' }
PhratchCategoryFiles class >> label [
	^'files'
]

{ #category : #'as yet unclassified' }
PhratchCategoryFiles class >> order [
	^9
]
