Class {
	#name : #PhratchCategoryControl,
	#superclass : #PhratchCategory,
	#category : #'Phratch-Categories'
}

{ #category : #'as yet unclassified' }
PhratchCategoryControl class >> color [
	^(Color h: 41 s: 0.85 v: 0.9)
]

{ #category : #'as yet unclassified' }
PhratchCategoryControl class >> label [
	^'control'
]

{ #category : #'as yet unclassified' }
PhratchCategoryControl class >> order [
	^2
]
