"
I represent the Operators category of phratch
"
Class {
	#name : #PhratchCategoryOperators,
	#superclass : #PhratchCategory,
	#category : #'Phratch-Categories'
}

{ #category : #accessing }
PhratchCategoryOperators class >> color [
	^(Color h: 93 s: 0.9 v: 0.76)
]

{ #category : #accessing }
PhratchCategoryOperators class >> label [
	^'operators'
]

{ #category : #accessing }
PhratchCategoryOperators class >> order [
	^6
]
