"
I stores metadata on true and false positive critics. These meta data are used by the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPhratchDebugger,
	#superclass : #Object,
	#category : #PhratchDebugger
}

{ #category : #'meta data' }
ManifestPhratchDebugger class >> rejectClasses [
^ #()
]

{ #category : #'meta data' }
ManifestPhratchDebugger class >> rejectRules [
^ #()
]
