Class {
	#name : #PhratchCategoryGopro,
	#superclass : #PhratchCategory,
	#instVars : [
		'gopro'
	],
	#category : #PhratchGoPro
}

{ #category : #'as yet unclassified' }
PhratchCategoryGopro class >> color [

	^ Color blue
]

{ #category : #'as yet unclassified' }
PhratchCategoryGopro class >> label [

	^ 'gopro'
]

{ #category : #'as yet unclassified' }
PhratchCategoryGopro class >> order [

	^99
]
