Class {
	#name : #PhratchCategoryBlockeditor,
	#superclass : #PhratchCategory,
	#category : #PhratchBlockeditor
}

{ #category : #'as yet unclassified' }
PhratchCategoryBlockeditor class >> color [ ^ Color red
]

{ #category : #'as yet unclassified' }
PhratchCategoryBlockeditor class >> label [ ^ 'blockeditor'
]

{ #category : #'as yet unclassified' }
PhratchCategoryBlockeditor class >> order [ ^ 12
]
