Class {
	#name : #PhratchCategoryMinecraftDemo,
	#superclass : #PhratchCategory,
	#category : #MinecraftPhratch
}

{ #category : #'as yet unclassified' }
PhratchCategoryMinecraftDemo class >> color [

	^ Color blue
]

{ #category : #'as yet unclassified' }
PhratchCategoryMinecraftDemo class >> label [

	^ 'minecraft demo'
]

{ #category : #'as yet unclassified' }
PhratchCategoryMinecraftDemo class >> order [

	^99
]
