"
I stores metadata on true and false positive critics. These meta data are used by the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestPhratchSensing,
	#superclass : #Object,
	#category : #PhratchSensing
}

{ #category : #'meta data' }
ManifestPhratchSensing class >> rejectClasses [
^ #()
]

{ #category : #'meta data' }
ManifestPhratchSensing class >> rejectRules [
^ #()
]
